use e2e-bootstrap.sh for workflow_dispatch BYOB tests
Signed-off-by: Ian Lewis <ianlewis@google.com>

diff --git a/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml b/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml
--- a/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml
+++ b/.github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml
@@ -2,6 +2,12 @@ on:
   schedule:
     - cron: "0 0 * * *"
   workflow_dispatch:
+    inputs:
+      trigger_build:
+        description: "internal: do not check"
+        required: false
+        default: false
+        type: boolean
 
 permissions: read-all
 
@@ -19,31 +25,44 @@ env:
   CHECKOUT_MESSAGE: "hello checkout"
 
 jobs:
-  # Dispatch
+  # Bootstrap
   ################################################################################
-  dispatch:
+
+  bootstrap:
     runs-on: ubuntu-latest
-    # NOTE: workflows are only scheduled on the main branch.
-    if: github.event_name == 'schedule'
+    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.trigger_build)
     permissions:
-      actions: write
       contents: write
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - run: ./.github/workflows/scripts/e2e-dispatch.sh
+      # Bumps the package version pushes, creates a git tag, and pushes the tag.
+      - run: ./.github/workflows/scripts/e2e-bootstrap.sh
 
-  if-dispatch-failed:
+  if-bootstrap-failed:
     runs-on: ubuntu-latest
-    needs: [dispatch]
-    if: always() && github.event_name == 'schedule' && needs.dispatch.result != 'success'
+    needs: [bootstrap]
+    if: always() && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.trigger_build)) && needs.bootstrap.result != 'success'
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - run: ./.github/workflows/scripts/e2e-report-failure.sh
 
   # Main workflow
   ################################################################################
+
+  # Shim determines if the rest of the workflow should run.
+  # NOTE: it should only use the `if` to determine this and all downstream jobs
+  #      should depend on this job.
+  shim:
+    # NOTE: this must be kept in sync with the if-failed job.
+    if: github.event_name == 'workflow_dispatch' && inputs.trigger_build
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          echo "event: ${GITHUB_EVENT_NAME}"
+          echo "ref: ${GITHUB_REF}"
+
   build:
-    if: github.event_name == 'workflow_dispatch'
+    needs: [shim]
     permissions:
       id-token: write # For signing
       contents: write # For asset uploads
@@ -63,7 +82,6 @@ jobs:
   verify:
     runs-on: ubuntu-latest
     needs: [build]
-    if: github.event_name == 'workflow_dispatch'
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
@@ -85,7 +103,7 @@ jobs:
   if-succeeded:
     runs-on: ubuntu-latest
     needs: [build, verify]
-    if: github.event_name == 'workflow_dispatch' && needs.build.result == 'success' && needs.verify.result == 'success'
+    if: needs.build.result == 'success' && needs.publish.result == 'success' && needs.verify.result == 'success'
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - run: ./.github/workflows/scripts/e2e-report-success.sh
@@ -93,7 +111,7 @@ jobs:
   if-failed:
     runs-on: ubuntu-latest
     needs: [build, verify]
-    if: always() && github.event_name == 'workflow_dispatch' && (needs.build.result == 'failure' || needs.verify.result == 'failure')
+    if: always() && github.event_name == 'workflow_dispatch' && inputs.trigger_build && (needs.build.result != 'success' || needs.publish.result != 'success' || needs.verify.result != 'success')
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - run: ./.github/workflows/scripts/e2e-report-failure.sh
