Multiple updates
Signed-off-by: AdamKorcz <44787359+AdamKorcz@users.noreply.github.com>

diff --git a/.github/workflows/e2e.maven.workflow_dispatch.main.default.slsa3.yml b/.github/workflows/e2e.maven.workflow_dispatch.main.default.slsa3.yml
--- a/.github/workflows/e2e.maven.workflow_dispatch.main.default.slsa3.yml
+++ b/.github/workflows/e2e.maven.workflow_dispatch.main.default.slsa3.yml
@@ -29,10 +29,24 @@ jobs:
   if-bootstrap-failed:
     runs-on: ubuntu-latest
     needs: [bootstrap]
-    if: always() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && needs.bootstrap.result != 'success'
+    if: always() && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.trigger_build)) && needs.bootstrap.result != 'success'
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
       - run: ./.github/workflows/scripts/e2e-report-failure.sh
+  
+  # Main workflow
+  ################################################################################
+  # Shim determines if the rest of the workflow should run.
+  # NOTE: it should only use the `if` to determine this and all downstream jobs
+  #      should depend on this job.
+  shim:
+    # NOTE: this must be kept in sync with the if-failed job.
+    if: github.event_name == 'workflow_dispatch' && inputs.trigger_build
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          echo "event: ${GITHUB_EVENT_NAME}"
+          echo "ref: ${GITHUB_REF}"
 
   build:
     #runs-on: ubuntu-latest
@@ -66,4 +80,20 @@ jobs:
           ARTIFACT_VERSION: ${{ needs.bootstrap.outputs.artifact-version}}
           PROVENANCE: "slsa-attestations/${{ needs.build.outputs.provenance-download-name }}/test-java-project-${{ needs.bootstrap.outputs.artifact-version}}.jar.build.slsa"
           BUILDER_TAG: "v2.0.0"
+          EXPECTED_ARTIFACT_OUTPUT: "Hello world!"
         run: ./.github/workflows/scripts/e2e.maven.default.verify.sh
+  if-succeeded:
+    runs-on: ubuntu-latest
+    needs: [build, verify]
+    if: needs.build.result == 'success' && needs.publish.result == 'success' && needs.verify.result == 'success'
+    steps:
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - run: ./.github/workflows/scripts/e2e-report-success.sh
+
+  if-failed:
+    runs-on: ubuntu-latest
+    needs: [build, verify]
+    if: always() && github.event_name == 'workflow_dispatch' && inputs.trigger_build && (needs.build.result != 'success' || needs.publish.result != 'success' || needs.verify.result != 'success')
+    steps:
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - run: ./.github/workflows/scripts/e2e-report-failure.sh
